# Generated by Django 5.2.7 on 2025-11-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='multi_currency',
            field=models.BooleanField(default=False, help_text='Enable multi-currency support (Beta feature)'),
        ),
    ]
