# Generated by Django 5.2.7 on 2025-11-13 21:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total income for this month', max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total expenses for this month', max_digits=12)),
                ('net_surplus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net surplus (income - expenses)', max_digits=12)),
                ('savings_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Savings rate as percentage of income', max_digits=5)),
                ('wallets_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of wallet balances: {"spending": 1500.00, "saving": 5000.00, ...}')),
                ('liquid_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of spending + cash wallet balances', max_digits=12)),
                ('reserved_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of saving + investment wallet balances', max_digits=12)),
                ('total_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all wallet balances', max_digits=12)),
                ('spent_per_categories', models.JSONField(blank=True, default=list, help_text='List of category spending: [{"category_id": 1, "category_name": "Food", "amount": 500.00, "percentage": 20.5}, ...]')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_current_month', models.BooleanField(default=False, help_text='True only for the current month (only one per user should be True)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Summary',
                'verbose_name_plural': 'Monthly Summaries',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['user', 'year', 'month'], name='analytics_m_user_id_378b0f_idx'), models.Index(fields=['user', 'is_current_month'], name='analytics_m_user_id_a39043_idx')],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
