# Generated by Django 5.2.7 on 2025-10-16 11:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='type',
            field=models.CharField(choices=[('spending', 'Spending'), ('saving', 'Saving'), ('cash', 'Cash'), ('investment', 'Investment')], default='spending', max_length=15),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Must be positive', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='transactions.wallet')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='transactions.wallet')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['-date'], name='transaction_date_a8cd83_idx'), models.Index(fields=['from_wallet', '-date'], name='transaction_from_wa_686577_idx'), models.Index(fields=['to_wallet', '-date'], name='transaction_to_wall_e8aa55_idx')],
            },
        ),
    ]
