import {
  Baby, Glasses, Moon, Sun, Award, Building, Building2, Cake, Cookie, CreditCard, Gift, HandCoins, Handshake, KeyRound, KeySquare, Mail, Shield, Star, Tag, Ticket, 
  VenetianMask, Wallet, WalletCards, WalletMinimal, Wrench, Bird, Bone, Bug, Cat, Dog, Egg, Fish, Origami, Panda, PawPrint, Rabbit, Snail, Squirrel, Turtle, 
  BrickWall, Castle, Church, Factory, Fence, GraduationCap, Hospital, Hotel, House, HouseHeart, HousePlug, HouseWifi, Landmark, School, Store, Theater, University, 
  UtilityPole, Warehouse, ChartNoAxesCombined, ChartPie, Camera, CassetteTape, Newspaper, Notebook, Phone, Presentation, Spotlight, Tv, Video, Videotape, Cable, Headphones, 
  Monitor, Smartphone, Wifi, SatelliteDish, Zap, PenTool, Pencil, Sparkles, Cylinder, PencilRuler, Pen, Paperclip, Ruler, Scissors, Ratio, Magnet, PaintRoller, PaintBucket, 
  Paintbrush, PaintbrushVertical, Palette, Brush, Stamp, SwatchBook, Binoculars, Book, BookOpen, BookOpenText, Box, Folder, Gem, LibraryBig, Keyboard, Package, 
  PackageOpen, Plug, Plug2, Puzzle, Rocket, Scroll, ScrollText, Telescope, Unplug, AlarmClock, Drill, Drum, Laptop, LaptopMinimal, Piano, Printer, Toilet, Wallpaper, 
  BicepsFlexed, HandFist, HandMetal, Heart, HeartCrack, Laugh, LeafyGreen, PartyPopper, Ribbon, Salad, Archive, Music, Music2, Banknote, BanknoteArrowDown, BanknoteArrowUp, 
  Bitcoin, PiggyBank, Receipt, ReceiptEuro, ReceiptText, ReceiptPoundSterling, Amphora, Apple, Banana, Barrel, Bean, Beef, Beer, BottleWine, CakeSlice, Candy, Carrot, ChefHat, 
  Cherry, Citrus, Coffee, CookingPot, Croissant, CupSoda, Dessert, Drumstick, EggFried, GlassWater, Grape, Ham, Hamburger, HandPlatter, Hop, IceCreamCone, Martini, 
  Microwave, Milk, Nut, Pizza, Popcorn, Popsicle, Refrigerator, Sandwich, Soup, Tractor, Utensils, UtensilsCrossed, Vegan, Wheat, Wine, Anvil, Axe, Backpack, BowArrow, Clover, 
  Dices, Feather, Flame, FlameKindling, FlaskConical, Flower, Gamepad2, Ghost, Mountain, Pickaxe, Signpost, Spade, Sprout, Sword, ToyBrick, Trophy, Volleyball, AirVent, 
  Armchair, Bed, BedDouble, BedSingle, DoorClosed, DoorOpen, Fan, Hammer, Heater, Lamp, LampCeiling, LampFloor, LampDesk, RockingChair, Rose, ShowerHead, 
  ToolCase, WashingMachine, WavesLadder, MailOpen, Mailbox, Mails, Trash, Cone, Pyramid, Weight, Ambulance, Bandage, BriefcaseMedical, Cigarette, Ear, HeartPulse, Microscope, 
  Pill, PillBottle, Stethoscope, Syringe, Brain, Antenna, Drama, Film, Guitar, Image, Megaphone, MicVocal, Youtube, Cannabis, Caravan, Flower2, MountainSnow, Shovel, Shrub, Tent, 
  TentTree, TreePalm, TreePine, Trees, Dumbbell, Earth, EvCharger, FerrisWheel, Fuel, Gavel, Globe, Map, Pin, Scale, Ship, ShipWheel, TrainFrontTunnel, TrainTrack, 
  Instagram, Lightbulb, Atom, Gauge, Pipette, Satellite, TestTubeDiagonal, Snowflake, Club, Cross, Cuboid, Triangle, Octagon, Shapes, Pentagon, Handbag, Shirt, ShoppingBag, 
  ShoppingBasket, ShoppingCart, TicketPercent, NotebookText, Rss, Medal, Recycle, Wind, Clipboard, BookMarked, Sheet, Watch, BaggageClaim, Bike, Briefcase, BriefcaseBusiness, 
  BriefcaseConveyorBelt, Bus, BusFront, CableCar, Car, CarFront, CarTaxiFront, ParkingCircle, ParkingSquare, Container, Forklift, Luggage, Motorbike, Plane, PlaneLanding, 
  PlaneTakeoff, Sailboat, Tickets, TicketsPlane, TrafficCone, TrainFront, TramFront, Truck, Bath, ConciergeBell, MapPinned, Bubbles, Cloud, CloudRain, Droplets, Rainbow, 
  Thermometer, ThermometerSnowflake, ThermometerSun, Umbrella, Tablet, Train, DollarSign, Activity, Droplet
} from 'lucide-react';

// Preset categories for Dough expense tracker
export const PRESET_CATEGORIES = {
  expense: [
    { name: 'Eating Out', icon: Utensils, iconName: 'Utensils' },
    { name: 'Groceries', icon: ShoppingBasket, iconName: 'ShoppingBasket' },
    { name: 'Takeout & Delivery', icon: Pizza, iconName: 'Pizza' },
    { name: 'Supermarket', icon: ShoppingCart, iconName: 'ShoppingCart' },
    { name: 'Bakery', icon: Croissant, iconName: 'Croissant' },
    { name: 'Farmers Market', icon: Carrot, iconName: 'Carrot' },
    { name: 'Coffee', icon: Coffee, iconName: 'Coffee' },
    { name: 'Drinks', icon: Wine, iconName: 'Wine' },
    { name: 'Car', icon: Car, iconName: 'Car' },
    { name: 'Fuel', icon: Fuel, iconName: 'Fuel' },
    { name: 'Parking', icon: ParkingSquare, iconName: 'ParkingSquare' },
    { name: 'Transportation', icon: TrainFront, iconName: 'TrainFront' },
    { name: 'Taxi', icon: CarTaxiFront, iconName: 'CarTaxiFront' },
    { name: 'Rent', icon: House, iconName: 'House' },
    { name: 'Electricity', icon: Zap, iconName: 'Zap' },
    { name: 'Water', icon: Droplet, iconName: 'Droplet' },
    { name: 'Heating', icon: Flame, iconName: 'Flame' },
    { name: 'Internet', icon: Wifi, iconName: 'Wifi' },
    { name: 'Bills', icon: ScrollText, iconName: 'ScrollText' },
    { name: 'Phone', icon: Smartphone, iconName: 'Smartphone' },
    { name: 'Building Fees', icon: Building, iconName: 'Building'},
    { name: 'Shopping', icon: ShoppingBag, iconName: 'ShoppingBag' },
    { name: 'Clothing', icon: Shirt, iconName: 'Shirt' },
    { name: 'Home Maintenance', icon: Hammer, iconName: 'Hammer' },
    { name: 'Home Decor', icon: Armchair, iconName: 'Armchair' },
    { name: 'Appliances', icon: Refrigerator, iconName: 'Refrigerator' },
    { name: 'Healthcare', icon: Hospital, iconName: 'Hospital' },
    { name: 'Medication', icon: Pill, iconName: 'Pill' },
    { name: 'Fitness', icon: Dumbbell, iconName: 'Dumbbell' },
    { name: 'Education', icon: GraduationCap, iconName: 'GraduationCap' },
    { name: 'Personal Care', icon: Sparkles, iconName: 'Sparkles' },
    { name: 'Beauty', icon: Gem, iconName: 'Gem' },
    { name: 'Subscriptions', icon: Scroll, iconName: 'Scroll' },
    { name: 'Travel', icon: Plane, iconName: 'Plane' },
    { name: 'Flights', icon: TicketsPlane, iconName: 'TicketsPlane' },
    { name: 'Accomodation', icon: Bed, iconName: 'Bed' },
    { name: 'Courier Services', icon: PackageOpen, iconName: 'PackageOpen' },
    { name: 'Entertainment', icon: Film, iconName: 'Film' },
    { name: 'Hobbies', icon: Palette, iconName: 'Palette' },
    { name: 'Electronics', icon: Cable, iconName: 'Cable' },
    { name: 'Laundry', icon: WashingMachine, iconName: 'WashingMachine' },
    { name: 'Gifts', icon: Gift, iconName: 'Gift' },
    { name: 'Pet Care', icon: PawPrint, iconName: 'PawPrint' },
    { name: 'Childcare', icon: Baby, iconName: 'Baby' },
    { name: 'Car Maintenance', icon: Wrench, iconName: 'Wrench' },
    { name: 'Insurance', icon: Shield, iconName: 'Shield' },
    { name: 'Taxes', icon: Receipt, iconName: 'Receipt' },
    { name: 'Mortgage', icon: Landmark, iconName: 'Landmark' },
    { name: 'Student Loan', icon: University, iconName: 'University' },
    { name: 'Donations', icon: HandCoins, iconName: 'HandCoins' },
    { name: 'Legal Services', icon: Stamp, iconName: 'Stamp' },
    { name: 'Other Expenses', icon: Folder, iconName: 'Folder' },
  ],
  income: [
    { name: 'Salary', icon: Briefcase, iconName: 'Briefcase' },
    { name: 'Freelance', icon: Laptop, iconName: 'Laptop' },
    { name: 'Business', icon: BriefcaseBusiness, iconName: 'BriefcaseBusiness' },
    { name: 'Investments', icon: ChartNoAxesCombined, iconName: 'ChartNoAxesCombined' },
    { name: 'Rental Income', icon: House, iconName: 'House' },
    { name: 'Bonus', icon: PartyPopper, iconName: 'PartyPopper' },
    { name: 'Gifts', icon: Gift, iconName: 'Gift' },
    { name: 'Cashback', icon: CreditCard, iconName: 'CreditCard' },
    { name: 'Other Income', icon: Folder, iconName: 'Folder' },
  ],
};

// Icon name to component mapping (for database storage/retrieval)
export const ICON_MAP = {
'Activity': Activity,
'AirVent': AirVent,
'AlarmClock': AlarmClock,
'Ambulance': Ambulance,
'Amphora': Amphora,
'Antenna': Antenna,
'Anvil': Anvil,
'Apple': Apple,
'Archive': Archive,
'Armchair': Armchair,
'Atom': Atom,
'Award': Award,
'Axe': Axe,
'Baby': Baby,
'Backpack': Backpack,
'BaggageClaim': BaggageClaim,
'Banana': Banana,
'Bandage': Bandage,
'Banknote': Banknote,
'BanknoteArrowDown': BanknoteArrowDown,
'BanknoteArrowUp': BanknoteArrowUp,
'Barrel': Barrel,
'Bath': Bath,
'Bean': Bean,
'Bed': Bed,
'BedDouble': BedDouble,
'BedSingle': BedSingle,
'Beef': Beef,
'Beer': Beer,
'BicepsFlexed': BicepsFlexed,
'Bike': Bike,
'Binoculars': Binoculars,
'Bird': Bird,
'Bitcoin': Bitcoin,
'Bone': Bone,
'Book': Book,
'BookMarked': BookMarked,
'BookOpen': BookOpen,
'BookOpenText': BookOpenText,
'BottleWine': BottleWine,
'BowArrow': BowArrow,
'Box': Box,
'Brain': Brain,
'BrickWall': BrickWall,
'Briefcase': Briefcase,
'BriefcaseBusiness': BriefcaseBusiness,
'BriefcaseConveyorBelt': BriefcaseConveyorBelt,
'BriefcaseMedical': BriefcaseMedical,
'Brush': Brush,
'Bubbles': Bubbles,
'Bug': Bug,
'Building': Building,
'Building2': Building2,
'Bus': Bus,
'BusFront': BusFront,
'Cable': Cable,
'CableCar': CableCar,
'Cake': Cake,
'CakeSlice': CakeSlice,
'Camera': Camera,
'Candy': Candy,
'Cannabis': Cannabis,
'Car': Car,
'CarFront': CarFront,
'CarTaxiFront': CarTaxiFront,
'Caravan': Caravan,
'Carrot': Carrot,
'CassetteTape': CassetteTape,
'Castle': Castle,
'Cat': Cat,
'ChartNoAxesCombined': ChartNoAxesCombined,
'ChartPie': ChartPie,
'ChefHat': ChefHat,
'Cherry': Cherry,
'Church': Church,
'Cigarette': Cigarette,
'Citrus': Citrus,
'Clipboard': Clipboard,
'Cloud': Cloud,
'CloudRain': CloudRain,
'Clover': Clover,
'Club': Club,
'Coffee': Coffee,
'ConciergeBell': ConciergeBell,
'Cone': Cone,
'Container': Container,
'Cookie': Cookie,
'CookingPot': CookingPot,
'CreditCard': CreditCard,
'Croissant': Croissant,
'Cross': Cross,
'Cuboid': Cuboid,
'CupSoda': CupSoda,
'Cylinder': Cylinder,
'Dessert': Dessert,
'Dices': Dices,
'Dog': Dog,
'DollarSign': DollarSign,
'DoorClosed': DoorClosed,
'DoorOpen': DoorOpen,
'Drama': Drama,
'Drill': Drill,
'Droplet': Droplet,
'Droplets': Droplets,
'Drum': Drum,
'Drumstick': Drumstick,
'Dumbbell': Dumbbell,
'Ear': Ear,
'Earth': Earth,
'Egg': Egg,
'EggFried': EggFried,
'EvCharger': EvCharger,
'Factory': Factory,
'Fan': Fan,
'Feather': Feather,
'Fence': Fence,
'FerrisWheel': FerrisWheel,
'Film': Film,
'Fish': Fish,
'Flame': Flame,
'FlameKindling': FlameKindling,
'FlaskConical': FlaskConical,
'Flower': Flower,
'Flower2': Flower2,
'Folder': Folder,
'Forklift': Forklift,
'Fuel': Fuel,
'Gamepad2': Gamepad2,
'Gauge': Gauge,
'Gavel': Gavel,
'Gem': Gem,
'Ghost': Ghost,
'Gift': Gift,
'GlassWater': GlassWater,
'Glasses': Glasses,
'Globe': Globe,
'GraduationCap': GraduationCap,
'Grape': Grape,
'Guitar': Guitar,
'Ham': Ham,
'Hamburger': Hamburger,
'Hammer': Hammer,
'HandCoins': HandCoins,
'HandFist': HandFist,
'HandMetal': HandMetal,
'HandPlatter': HandPlatter,
'Handbag': Handbag,
'Handshake': Handshake,
'Headphones': Headphones,
'Heart': Heart,
'HeartCrack': HeartCrack,
'HeartPulse': HeartPulse,
'Heater': Heater,
'Hop': Hop,
'Hospital': Hospital,
'Hotel': Hotel,
'House': House,
'HouseHeart': HouseHeart,
'HousePlug': HousePlug,
'HouseWifi': HouseWifi,
'IceCreamCone': IceCreamCone,
'Image': Image,
'Instagram': Instagram,
'KeyRound': KeyRound,
'KeySquare': KeySquare,
'Keyboard': Keyboard,
'Lamp': Lamp,
'LampCeiling': LampCeiling,
'LampDesk': LampDesk,
'LampFloor': LampFloor,
'Landmark': Landmark,
'Laptop': Laptop,
'LaptopMinimal': LaptopMinimal,
'Laugh': Laugh,
'LeafyGreen': LeafyGreen,
'LibraryBig': LibraryBig,
'Lightbulb': Lightbulb,
'Luggage': Luggage,
'Magnet': Magnet,
'Mail': Mail,
'MailOpen': MailOpen,
'Mailbox': Mailbox,
'Mails': Mails,
'Map': Map,
'MapPinned': MapPinned,
'Martini': Martini,
'Medal': Medal,
'Megaphone': Megaphone,
'MicVocal': MicVocal,
'Microscope': Microscope,
'Microwave': Microwave,
'Milk': Milk,
'Monitor': Monitor,
'Moon': Moon,
'Motorbike': Motorbike,
'Mountain': Mountain,
'MountainSnow': MountainSnow,
'Music': Music,
'Music2': Music2,
'Newspaper': Newspaper,
'Notebook': Notebook,
'NotebookText': NotebookText,
'Nut': Nut,
'Octagon': Octagon,
'Origami': Origami,
'Package': Package,
'PackageOpen': PackageOpen,
'PaintBucket': PaintBucket,
'PaintRoller': PaintRoller,
'Paintbrush': Paintbrush,
'PaintbrushVertical': PaintbrushVertical,
'Palette': Palette,
'Panda': Panda,
'Paperclip': Paperclip,
'ParkingCircle': ParkingCircle,
'ParkingSquare': ParkingSquare,
'PartyPopper': PartyPopper,
'PawPrint': PawPrint,
'Pen': Pen,
'PenTool': PenTool,
'Pencil': Pencil,
'PencilRuler': PencilRuler,
'Pentagon': Pentagon,
'Phone': Phone,
'Piano': Piano,
'Pickaxe': Pickaxe,
'PiggyBank': PiggyBank,
'Pill': Pill,
'PillBottle': PillBottle,
'Pin': Pin,
'Pipette': Pipette,
'Pizza': Pizza,
'Plane': Plane,
'PlaneLanding': PlaneLanding,
'PlaneTakeoff': PlaneTakeoff,
'Plug': Plug,
'Plug2': Plug2,
'Popcorn': Popcorn,
'Popsicle': Popsicle,
'Presentation': Presentation,
'Printer': Printer,
'Puzzle': Puzzle,
'Pyramid': Pyramid,
'Rabbit': Rabbit,
'Rainbow': Rainbow,
'Ratio': Ratio,
'Receipt': Receipt,
'ReceiptEuro': ReceiptEuro,
'ReceiptPoundSterling': ReceiptPoundSterling,
'ReceiptText': ReceiptText,
'Recycle': Recycle,
'Refrigerator': Refrigerator,
'Ribbon': Ribbon,
'Rocket': Rocket,
'RockingChair': RockingChair,
'Rose': Rose,
'Rss': Rss,
'Ruler': Ruler,
'Sailboat': Sailboat,
'Salad': Salad,
'Sandwich': Sandwich,
'Satellite': Satellite,
'SatelliteDish': SatelliteDish,
'Scale': Scale,
'School': School,
'Scissors': Scissors,
'Scroll': Scroll,
'ScrollText': ScrollText,
'Shapes': Shapes,
'Sheet': Sheet,
'Shield': Shield,
'Ship': Ship,
'ShipWheel': ShipWheel,
'Shirt': Shirt,
'ShoppingBag': ShoppingBag,
'ShoppingBasket': ShoppingBasket,
'ShoppingCart': ShoppingCart,
'Shovel': Shovel,
'ShowerHead': ShowerHead,
'Shrub': Shrub,
'Signpost': Signpost,
'Smartphone': Smartphone,
'Snail': Snail,
'Snowflake': Snowflake,
'Soup': Soup,
'Spade': Spade,
'Sparkles': Sparkles,
'Spotlight': Spotlight,
'Sprout': Sprout,
'Squirrel': Squirrel,
'Stamp': Stamp,
'Star': Star,
'Stethoscope': Stethoscope,
'Store': Store,
'Sun': Sun,
'SwatchBook': SwatchBook,
'Sword': Sword,
'Syringe': Syringe,
'Tablet': Tablet,
'Tag': Tag,
'Telescope': Telescope,
'Tent': Tent,
'TentTree': TentTree,
'TestTubeDiagonal': TestTubeDiagonal,
'Theater': Theater,
'Thermometer': Thermometer,
'ThermometerSnowflake': ThermometerSnowflake,
'ThermometerSun': ThermometerSun,
'Ticket': Ticket,
'TicketPercent': TicketPercent,
'Tickets': Tickets,
'TicketsPlane': TicketsPlane,
'Toilet': Toilet,
'ToolCase': ToolCase,
'ToyBrick': ToyBrick,
'Tractor': Tractor,
'TrafficCone': TrafficCone,
'Train': Train,
'TrainFront': TrainFront,
'TrainFrontTunnel': TrainFrontTunnel,
'TrainTrack': TrainTrack,
'TramFront': TramFront,
'Trash': Trash,
'TreePalm': TreePalm,
'TreePine': TreePine,
'Trees': Trees,
'Triangle': Triangle,
'Trophy': Trophy,
'Truck': Truck,
'Turtle': Turtle,
'Tv': Tv,
'Umbrella': Umbrella,
'University': University,
'Unplug': Unplug,
'Utensils': Utensils,
'UtensilsCrossed': UtensilsCrossed,
'UtilityPole': UtilityPole,
'Vegan': Vegan,
'VenetianMask': VenetianMask,
'Video': Video,
'Videotape': Videotape,
'Volleyball': Volleyball,
'Wallet': Wallet,
'WalletCards': WalletCards,
'WalletMinimal': WalletMinimal,
'Wallpaper': Wallpaper,
'Warehouse': Warehouse,
'WashingMachine': WashingMachine,
'Watch': Watch,
'WavesLadder': WavesLadder,
'Weight': Weight,
'Wheat': Wheat,
'Wifi': Wifi,
'Wind': Wind,
'Wine': Wine,
'Wrench': Wrench,
'Youtube': Youtube,
'Zap': Zap
};

// Helper function to get icon component from name
export const getIconComponent = (iconName) => {
  return ICON_MAP[iconName] || Folder; // Default to Folder if not found
};

// Common currencies for currency picker
export const CURRENCIES = [
  { code: 'EUR', name: 'Euro', symbol: '€' },
  { code: 'USD', name: 'US Dollar', symbol: '$' },
  { code: 'GBP', name: 'British Pound', symbol: '£' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥' },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'Fr' },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$' },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$' },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹' },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$' },
  { code: 'MXN', name: 'Mexican Peso', symbol: '$' },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R' },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr' },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr' },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr' },
  { code: 'PLN', name: 'Polish Zloty', symbol: 'zł' },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽' },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺' },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩' },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$' },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$' },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$' },
  { code: 'THB', name: 'Thai Baht', symbol: '฿' },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM' },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp' },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱' },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč' },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft' },
  { code: 'ILS', name: 'Israeli Shekel', symbol: '₪' },
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ' },
];

export default PRESET_CATEGORIES;
