# Generated by Django 5.2.7 on 2025-11-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_per_user',
        ),
    ]
