# Generated by Django 5.2.7 on 2025-10-16 18:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_wallet_type_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='wallet',
        ),
        migrations.AddField(
            model_name='budget',
            name='period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('6-month', '6-Month'), ('yearly', 'Yearly')], default='monthly', max_length=15),
        ),
        migrations.AddField(
            model_name='budget',
            name='reset',
            field=models.BooleanField(default=False, help_text='True for recurring budgets'),
        ),
        migrations.AddField(
            model_name='budget',
            name='rollover',
            field=models.BooleanField(default=False, help_text='Rollover remaining budget to next period (only if reset is True)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
