# Generated by Django 5.2.7 on 2025-11-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_category_unique_category_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='use_savings',
            field=models.BooleanField(default=False, help_text='Whether to use savings/reserved balance for this purchase'),
        ),
    ]
