# Generated by Django 5.2.7 on 2025-11-05 08:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_budget_categories_alter_budget_name_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='is_recurring',
        ),
        migrations.AlterField(
            model_name='template',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default amount for this template (can be zero)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='template',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_templates', to=settings.AUTH_USER_MODEL),
        ),
    ]
