# Generated by Django 5.2.7 on 2025-10-19 10:18

import django.core.validators
import django.db.models.deletion
import month.models
import transactions.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_add_recurrence_and_refactor_upcoming'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-start_month']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='description',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recurrence_end_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recurrence_pattern',
        ),
        migrations.RemoveField(
            model_name='upcomingtransaction',
            name='posted_transaction',
        ),
        migrations.AddField(
            model_name='budget',
            name='start_month',
            field=month.models.MonthField(default=transactions.models.get_current_month),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurrence',
            field=models.CharField(blank=True, choices=[('', 'No Recurrence'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='', help_text='Recurrence pattern for recurring transactions', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurrence_parent',
            field=models.ForeignKey(blank=True, help_text='Parent transaction for recurring transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrence_children', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='budget',
            name='reset',
            field=models.BooleanField(default=True, help_text='True for recurring budgets'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#9E9E9E', help_text='Hex color code', max_length=7),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Must be positive', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'US Dollar ($)'), ('GBP', 'British Pound (£)'), ('JPY', 'Japanese Yen (¥)'), ('CHF', 'Swiss Franc (CHF)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('CNY', 'Chinese Yuan (¥)'), ('INR', 'Indian Rupee (₹)'), ('SEK', 'Swedish Krona (kr)'), ('NOK', 'Norwegian Krone (kr)'), ('DKK', 'Danish Krone (kr)'), ('PLN', 'Polish Zloty (zł)'), ('CZK', 'Czech Koruna (Kč)'), ('HUF', 'Hungarian Forint (Ft)')], default='EUR', max_length=3),
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('target', month.models.MonthField(help_text='Target month to purchase this item')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wishlist_items', to='transactions.category')),
            ],
            options={
                'ordering': ['target', '-priority', '-created_at'],
            },
        ),
    ]
