# Generated by Django 5.2.7 on 2025-10-19 10:26

import month.models
import transactions.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_budget_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='target',
            field=month.models.MonthField(default=transactions.models.get_current_month, help_text='Target month to purchase this item'),
        ),
    ]
