# Generated by Django 5.2.7 on 2025-10-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_remove_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recurrence',
            field=models.CharField(blank=True, choices=[('', 'No Recurrence'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default=None, help_text='Recurrence pattern for recurring transactions', max_length=10),
        ),
    ]
