# Generated by Django 5.2.7 on 2025-10-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_transaction_recurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recurrence',
            field=models.CharField(blank=True, choices=[('', 'No Recurrence'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='', help_text='Recurrence pattern for recurring transactions', max_length=10, null=True),
        ),
    ]
