# Generated by Django 5.2.7 on 2025-10-24 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_alter_transaction_recurrence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='desc',
            new_name='description',
        ),
    ]
