# Generated by Django 5.2.7 on 2025-10-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_rename_desc_transaction_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half-year', 'Half-Year'), ('yearly', 'Yearly')], default='monthly', max_length=15),
        ),
    ]
