# Generated by Django 5.2.7 on 2025-10-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_alter_budget_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upcomingtransaction',
            options={'ordering': ['date', '-created_at'], 'verbose_name': 'Upcoming Transaction', 'verbose_name_plural': 'Upcoming Transactions'},
        ),
    ]
