# Generated by Django 5.2.7 on 2025-10-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_alter_upcomingtransaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recurrence',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', help_text='Recurrence pattern for recurring transactions', max_length=10, null=True),
        ),
    ]
